export const PAGE_META = {
  landing: {
    title: 'Paddock — Personal Wealth Dashboard',
    description: 'Track net worth, understand progress, and model your long-term future with multi-currency tracking, visible assumptions, and projections that show the path ahead.',
    canonical: 'https://getpaddock.com/',
    ogType: 'website',
    jsonLd: {
      '@context': 'https://schema.org',
      '@type': 'WebSite',
      name: 'Paddock',
      url: 'https://getpaddock.com',
      description: 'Personal wealth dashboard with multi-currency net worth tracking, long-term projections, and visible assumptions.',
    },
  },
  guides_index: {
    title: 'Guides — Wealth Tracking & Planning | Paddock',
    description: 'Clear, practical guides on long-term wealth projections, multi-currency net worth tracking, and inflation-adjusted planning.',
    canonical: 'https://getpaddock.com/guides',
    ogType: 'website',
    jsonLd: {
      '@context': 'https://schema.org',
      '@type': 'CollectionPage',
      name: 'Paddock Guides',
      url: 'https://getpaddock.com/guides',
      description: 'Clear, practical guides on long-term wealth projections, multi-currency net worth tracking, and inflation-adjusted planning.',
      isPartOf: { '@type': 'WebSite', name: 'Paddock', url: 'https://getpaddock.com' },
    },
  },
  guide_multi_currency: {
    title: 'Multi-Currency Net Worth Tracking Explained | Paddock',
    description: 'How multi-currency net worth tracking works, why single-currency totals mislead, and how to keep your wealth dashboard accurate across GBP, USD, and EUR.',
    canonical: 'https://getpaddock.com/guides/multi-currency-net-worth-tracker',
    ogType: 'article',
    jsonLd: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: 'Multi-Currency Net Worth Tracking Explained',
      description: 'How multi-currency net worth tracking works, why single-currency totals mislead, and how to keep your wealth dashboard accurate across GBP, USD, and EUR.',
      url: 'https://getpaddock.com/guides/multi-currency-net-worth-tracker',
      inLanguage: 'en',
      isPartOf: { '@type': 'WebSite', name: 'Paddock', url: 'https://getpaddock.com' },
      publisher: { '@type': 'Organization', name: 'Paddock', url: 'https://getpaddock.com' },
    },
  },
  guide_long_term_projection: {
    title: 'How Long-Term Wealth Projections Work | Paddock',
    description: 'How long-term wealth projections work, what drives them, and how to use compound growth and contribution modelling to plan 5–40 years ahead.',
    canonical: 'https://getpaddock.com/guides/long-term-wealth-projection',
    ogType: 'article',
    jsonLd: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: 'How Long-Term Wealth Projections Actually Work',
      description: 'How long-term wealth projections work, what drives them, and how to use compound growth and contribution modelling to plan 5–40 years ahead.',
      url: 'https://getpaddock.com/guides/long-term-wealth-projection',
      inLanguage: 'en',
      isPartOf: { '@type': 'WebSite', name: 'Paddock', url: 'https://getpaddock.com' },
      publisher: { '@type': 'Organization', name: 'Paddock', url: 'https://getpaddock.com' },
    },
  },
  guide_inflation_adjusted: {
    title: 'Inflation-Adjusted Net Worth: Real vs Nominal | Paddock',
    description: 'Why inflation-adjusted net worth matters for long-term planning, with worked examples showing the difference between nominal and real-terms projections.',
    canonical: 'https://getpaddock.com/guides/inflation-adjusted-net-worth',
    ogType: 'article',
    jsonLd: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: 'Inflation-Adjusted Net Worth: Why Real Terms Matter',
      description: 'Why inflation-adjusted net worth matters for long-term planning, with worked examples showing the difference between nominal and real-terms projections.',
      url: 'https://getpaddock.com/guides/inflation-adjusted-net-worth',
      inLanguage: 'en',
      isPartOf: { '@type': 'WebSite', name: 'Paddock', url: 'https://getpaddock.com' },
      publisher: { '@type': 'Organization', name: 'Paddock', url: 'https://getpaddock.com' },
    },
  },
  privacy: {
    title: 'Privacy | Paddock',
    description: 'How Paddock handles your data: no ads, no bank linking, no tracking. Privacy built into the product.',
    canonical: 'https://getpaddock.com/privacy',
    ogType: 'website',
  },
  security: {
    title: 'Security | Paddock',
    description: 'How Paddock keeps your data secure: industry-standard authentication, Stripe billing, encrypted connections.',
    canonical: 'https://getpaddock.com/security',
    ogType: 'website',
  },
  terms: {
    title: 'Terms of Use | Paddock',
    description: 'Terms of use for Paddock, the personal wealth dashboard.',
    canonical: 'https://getpaddock.com/terms',
    ogType: 'website',
  },
  net_worth_tracker: {
    title: 'Net Worth Tracker — Paddock',
    description:
      'Track cash, investments, pensions, property and liabilities in one calm dashboard. Built for long-term wealth with privacy-first manual tracking.',
    canonical: 'https://getpaddock.com/net-worth-tracker',
    ogType: 'website',
  },
  track_isas_pensions_savings: {
    title: 'Track ISAs, Pensions and Savings — Paddock',
    description:
      'See ISAs, pensions and savings together in one calm wealth dashboard. Track long-term progress clearly with privacy-first manual tracking.',
    canonical: 'https://getpaddock.com/track-isas-pensions-savings',
    ogType: 'website',
  },
  spreadsheet_alternative: {
    title: 'Spreadsheet Alternative for Net Worth Tracking — Paddock',
    description:
      'Replace fragile spreadsheets with a calmer way to track net worth, progress and long-term wealth in one premium dashboard.',
    canonical: 'https://getpaddock.com/spreadsheet-alternative-net-worth-tracking',
    ogType: 'website',
  },
  how_to_track_net_worth: {
    title: 'How to Track Your Net Worth — Paddock',
    description:
      'Learn how to track your net worth clearly, including what to include, how often to update it, and why consistency matters more than noise.',
    canonical: 'https://getpaddock.com/how-to-track-your-net-worth',
    ogType: 'website',
  },
}