export const CANONICAL_ORIGIN = 'https://getpaddock.com'

const sharedToolLinks = [
  '/tools/pension-drawdown-calculator',
  '/tools/fire-number-calculator',
  '/tools/net-worth-calculator',
  '/guides',
  '/privacy',
]

export const PUBLIC_ROUTES = [
  {
    key: 'landing',
    path: '/',
    lastmod: '2026-05-07',
    targetKeyword: 'net worth tracker UK',
    secondaryKeywords: ['manual wealth tracker', 'privacy-first wealth tracking', 'Paddock wealth tracker'],
    intent: 'Find a private UK wealth tracking product',
    h1: 'Paddock wealth tracker',
    intro:
      'Paddock is a UK-first, privacy-first manual wealth tracker for ISAs, pensions, savings, investments, property and long-term goals. No bank linking required.',
    links: ['/tools', '/guides', '/net-worth-tracker', '/privacy', '/security'],
    priority: true,
  },
  {
    key: 'tools_hub',
    path: '/tools',
    lastmod: '2026-05-07',
    targetKeyword: 'UK wealth calculators',
    secondaryKeywords: ['pension calculator UK', 'FIRE calculator UK', 'net worth calculator UK'],
    intent: 'Choose a free UK wealth planning calculator',
    h1: 'Free UK wealth planning tools',
    intro:
      'Free calculators for UK pension drawdown, FIRE planning, ISA growth, retirement bridge planning and net worth tracking. No login required.',
    links: sharedToolLinks,
    priority: true,
  },
  {
    key: 'tools_net_worth',
    path: '/tools/net-worth-calculator',
    lastmod: '2026-05-07',
    targetKeyword: 'net worth calculator UK',
    secondaryKeywords: ['net worth tracker UK', 'track ISA and SIPP together', 'wealth tracker UK'],
    intent: 'Calculate assets minus liabilities and understand net worth',
    h1: 'Net worth calculator UK',
    intro:
      'Total cash, investments, pensions, ISAs, property and debts in one private net worth calculator, then track the full picture over time with Paddock.',
    links: ['/net-worth-tracker', '/tools/fire-number-calculator', '/guides/multi-currency-net-worth-tracker', '/privacy'],
    priority: true,
  },
  {
    key: 'tools_pension_drawdown',
    path: '/tools/pension-drawdown-calculator',
    lastmod: '2026-05-07',
    targetKeyword: 'pension drawdown calculator UK',
    secondaryKeywords: ['how long will my pension last', 'SIPP drawdown calculator', 'retirement income planner UK'],
    intent: 'Estimate how long a pension pot may last in drawdown',
    h1: 'Pension drawdown calculator UK',
    intro:
      'Estimate how long your pension pot could last using UK drawdown assumptions, withdrawal rates and retirement income planning scenarios.',
    links: ['/tools/fire-number-calculator', '/tools/retirement-bridge-calculator', '/guides/long-term-wealth-projection', '/privacy'],
    priority: true,
  },
  {
    key: 'tools_retirement_bridge',
    path: '/tools/retirement-bridge-calculator',
    lastmod: '2026-05-07',
    targetKeyword: 'ISA retirement bridge calculator UK',
    secondaryKeywords: ['retire before pension access UK', 'ISA bridge calculator', 'retirement income planner UK'],
    intent: 'Estimate accessible savings needed before pension access',
    h1: 'ISA retirement bridge calculator UK',
    intro:
      'Estimate the ISA, cash or accessible savings you may need to bridge the years between stopping work and accessing pension income.',
    links: ['/tools/pension-drawdown-calculator', '/tools/fire-number-calculator', '/guides/long-term-wealth-projection', '/track-isas-pensions-savings'],
  },
  {
    key: 'tools_fire_number',
    path: '/tools/fire-number-calculator',
    lastmod: '2026-05-07',
    targetKeyword: 'FIRE number calculator UK',
    secondaryKeywords: ['financial independence calculator UK', 'how much do I need to retire early UK', 'track financial independence UK'],
    intent: 'Calculate financial independence target and progress',
    h1: 'FIRE number calculator UK',
    intro:
      'Calculate your UK FIRE number from annual spending, withdrawal rate and current invested assets, then track progress toward financial independence.',
    links: ['/tools/net-worth-calculator', '/tools/pension-drawdown-calculator', '/guides/long-term-wealth-projection', '/net-worth-tracker'],
    priority: true,
  },
  {
    key: 'tools_isa_growth',
    path: '/tools/isa-growth-calculator',
    lastmod: '2026-05-07',
    targetKeyword: 'ISA growth calculator UK',
    secondaryKeywords: ['Stocks and Shares ISA calculator', 'ISA projection calculator', 'investment growth calculator UK'],
    intent: 'Project ISA growth from contributions and returns',
    h1: 'ISA growth calculator UK',
    intro:
      'Project how a Stocks and Shares ISA could grow over time from your current balance, monthly contributions and return assumptions.',
    links: ['/track-isas-pensions-savings', '/tools/net-worth-calculator', '/guides/inflation-adjusted-net-worth', '/privacy'],
  },
  {
    key: 'guides_index',
    path: '/guides',
    lastmod: '2026-05-07',
    targetKeyword: 'wealth tracking guides UK',
    secondaryKeywords: ['net worth planning UK', 'long-term wealth projection', 'manual wealth tracking'],
    intent: 'Learn how to track and plan wealth over time',
    h1: 'Paddock guides',
    intro:
      'Practical UK guides on net worth tracking, long-term projections, inflation, multi-currency accounts and privacy-first manual wealth tracking.',
    links: ['/guides/multi-currency-net-worth-tracker', '/guides/long-term-wealth-projection', '/guides/inflation-adjusted-net-worth', '/tools'],
    priority: true,
  },
  {
    key: 'guide_multi_currency',
    path: '/guides/multi-currency-net-worth-tracker',
    lastmod: '2026-05-07',
    targetKeyword: 'multi-currency net worth tracker',
    secondaryKeywords: ['track investments across currencies', 'UK wealth tracker', 'multi-currency portfolio tracker'],
    intent: 'Understand how to track wealth across currencies',
    h1: 'Multi-currency net worth tracker',
    intro:
      'A practical guide to tracking GBP, USD, EUR and other currency balances in one base-currency net worth view.',
    links: ['/tools/net-worth-calculator', '/guides/long-term-wealth-projection', '/guides/inflation-adjusted-net-worth', '/net-worth-tracker'],
  },
  {
    key: 'guide_long_term_projection',
    path: '/guides/long-term-wealth-projection',
    lastmod: '2026-05-07',
    targetKeyword: 'long-term wealth projection',
    secondaryKeywords: ['compound growth planning', 'retirement projection UK', 'financial independence projection'],
    intent: 'Learn how long-term wealth projections work',
    h1: 'How long-term wealth projections actually work',
    intro:
      'Learn how contributions, return assumptions, inflation and time horizon shape long-term wealth projections and retirement planning.',
    links: ['/tools/fire-number-calculator', '/tools/pension-drawdown-calculator', '/guides/inflation-adjusted-net-worth', '/tools'],
  },
  {
    key: 'guide_inflation_adjusted',
    path: '/guides/inflation-adjusted-net-worth',
    lastmod: '2026-05-07',
    targetKeyword: 'inflation-adjusted net worth',
    secondaryKeywords: ['real vs nominal wealth', 'inflation adjusted projection', 'retirement planning inflation'],
    intent: 'Understand real-terms wealth tracking',
    h1: 'Inflation-adjusted net worth',
    intro:
      'Understand the difference between nominal and real-terms wealth, and why inflation-adjusted projections matter for long-term planning.',
    links: ['/tools/isa-growth-calculator', '/guides/long-term-wealth-projection', '/tools/fire-number-calculator', '/net-worth-tracker'],
  },
  {
    key: 'net_worth_tracker',
    path: '/net-worth-tracker',
    lastmod: '2026-05-07',
    targetKeyword: 'net worth tracker UK',
    secondaryKeywords: ['manual wealth tracking app', 'wealth tracker UK', 'track wealth without connecting bank account'],
    intent: 'Find a UK net worth tracking product',
    h1: 'Net worth tracker UK',
    intro:
      'Track cash, investments, pensions, ISAs, property and liabilities in one private manual-entry dashboard without connecting your bank.',
    links: ['/tools/net-worth-calculator', '/best-net-worth-tracking-apps-uk', '/guides/multi-currency-net-worth-tracker', '/privacy'],
    priority: true,
  },
  {
    key: 'track_isas_pensions_savings',
    path: '/track-isas-pensions-savings',
    lastmod: '2026-05-07',
    targetKeyword: 'track ISA and SIPP together',
    secondaryKeywords: ['track ISAs pensions savings', 'UK wealth tracker', 'manual net worth tracker'],
    intent: 'Find a way to track UK account types together',
    h1: 'Track ISAs, pensions and savings together',
    intro:
      'Bring ISAs, pensions, SIPPs, savings and property into one long-term wealth view built for UK planning and manual privacy-first tracking.',
    links: ['/tools/isa-growth-calculator', '/tools/pension-drawdown-calculator', '/net-worth-tracker', '/privacy'],
  },
  {
    key: 'spreadsheet_alternative',
    path: '/spreadsheet-alternative-net-worth-tracking',
    lastmod: '2026-05-07',
    targetKeyword: 'spreadsheet alternative net worth tracking',
    secondaryKeywords: ['manual wealth tracking app', 'net worth tracker UK', 'privacy-first finance app UK'],
    intent: 'Replace spreadsheets for net worth tracking',
    h1: 'Spreadsheet alternative for net worth tracking',
    intro:
      'Replace fragile spreadsheet tabs with a structured manual wealth tracker for net worth, accounts, projections and long-term goals.',
    links: ['/tools/net-worth-calculator', '/how-to-track-your-net-worth', '/net-worth-tracker', '/privacy'],
  },
  {
    key: 'how_to_track_net_worth',
    path: '/how-to-track-your-net-worth',
    lastmod: '2026-05-07',
    targetKeyword: 'how to track your net worth',
    secondaryKeywords: ['how to track net worth manually', 'net worth calculator UK', 'wealth tracker UK'],
    intent: 'Learn a practical net worth tracking method',
    h1: 'How to track your net worth',
    intro:
      'A practical guide to tracking net worth manually, including what to include, how often to update and how to make the number useful.',
    links: ['/tools/net-worth-calculator', '/net-worth-tracker', '/spreadsheet-alternative-net-worth-tracking', '/privacy'],
  },
  {
    key: 'best_net_worth_apps_uk',
    path: '/best-net-worth-tracking-apps-uk',
    lastmod: '2026-05-07',
    targetKeyword: 'best net worth tracking app UK',
    secondaryKeywords: ['Emma alternative UK', 'Moneyhub alternative', 'best finance app without bank linking'],
    intent: 'Compare UK net worth tracking app options',
    h1: 'Best net worth tracking apps UK',
    intro:
      'An honest comparison of Paddock, Emma, Moneyhub and spreadsheets for UK users tracking ISAs, pensions, savings and multi-currency wealth.',
    links: ['/net-worth-tracker', '/why-i-track-wealth-manually-instead-of-using-open-banking-apps', '/tools/net-worth-calculator', '/privacy'],
    priority: true,
  },
  {
    key: 'founder_manual_tracking',
    path: '/why-i-track-wealth-manually-instead-of-using-open-banking-apps',
    lastmod: '2026-05-07',
    targetKeyword: 'open banking alternative',
    secondaryKeywords: ['manual wealth tracking app', 'privacy-first finance app UK', 'track wealth without connecting bank account'],
    intent: 'Understand why manual tracking can be preferable to bank linking',
    h1: 'Why I track wealth manually instead of using open banking apps',
    intro:
      'A founder note on manual wealth tracking, privacy, long-term planning and why Paddock does not require open banking connections.',
    links: ['/privacy', '/best-net-worth-tracking-apps-uk', '/tools/pension-drawdown-calculator', '/net-worth-tracker'],
    priority: true,
  },
  {
    key: 'privacy',
    path: '/privacy',
    lastmod: '2026-05-07',
    targetKeyword: 'privacy-first finance app UK',
    secondaryKeywords: ['manual wealth tracking app', 'best finance app without bank linking', 'no bank linking finance app'],
    intent: 'Understand Paddock privacy and data handling',
    h1: 'Privacy at Paddock',
    intro:
      'Paddock is built around manual input, no bank linking, no ads and no ad tracking for people who want a private wealth dashboard.',
    links: ['/security', '/terms', '/why-i-track-wealth-manually-instead-of-using-open-banking-apps', '/net-worth-tracker'],
  },
  {
    key: 'security',
    path: '/security',
    lastmod: '2026-05-07',
    targetKeyword: 'Paddock security',
    secondaryKeywords: ['wealth tracker security', 'private finance app security'],
    intent: 'Understand Paddock security posture',
    h1: 'Security at Paddock',
    intro:
      'How Paddock protects access, sessions, payments and connections for a private manual wealth tracking experience.',
    links: ['/privacy', '/terms', '/support', '/net-worth-tracker'],
  },
  {
    key: 'support',
    path: '/support',
    lastmod: '2026-05-07',
    targetKeyword: 'Paddock support',
    secondaryKeywords: ['Paddock contact', 'Paddock help'],
    intent: 'Contact Paddock for support',
    h1: 'Support',
    intro:
      'Contact Paddock support for account, billing, bug report or general product questions.',
    links: ['/privacy', '/terms', '/security', '/'],
  },
  {
    key: 'terms',
    path: '/terms',
    lastmod: '2026-05-07',
    targetKeyword: 'Paddock terms',
    secondaryKeywords: ['Paddock terms of use'],
    intent: 'Read Paddock legal terms',
    h1: 'Terms of use',
    intro:
      'Terms of use for Paddock, the manual-entry personal wealth dashboard.',
    links: ['/privacy', '/security', '/support', '/'],
  },
]

export const PUBLIC_ROUTE_MAP = Object.fromEntries(PUBLIC_ROUTES.map((route) => [route.key, route.path]))
export const PUBLIC_ROUTE_BY_PATH = Object.fromEntries(PUBLIC_ROUTES.map((route) => [route.path, route]))
